### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-turisteando-por-mexico#1]
[GestionDeProyectos_Gestion de Calidad (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-turisteando-por-mexico/files/12834622/GestionDeProyectos_Gestion.de.Calidad.1.pdf)

**Comment by mel-16** [comment]
> [GestionDeProyectos_Gestion de Calidad (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-turisteando-por-mexico/files/12834622/GestionDeProyectos_Gestion.de.Calidad.1.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
